### ISSUE TITLE
documentation help - set up the app as static pages for github.io/netlify/etc

### ISSUE THREAD

**Issue by kkdops** [schadokar/go-to-do-app#16]
Thanks  Shubham! for the great app. I look forward to host it on my personal github.io account.
I did see you gave 2 example offline hosting of this app. Would you mind adding the steps on how to create one? any reference is helpful.

**Comment by schadokar** [comment]
Sure @kkdops I will add it.

**Comment by schadokar** [comment]
Documentation is updated. 
I have wrote a complete tutorial on this. https://codesource.io/building-an-offline-to-do-app-with-react/
